# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data-postgres:/var/lib/postgresql/data

  app:
    image: "oven/bun"
    depends_on: ["db"]
    entrypoint: []
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    ports: ["3000:3000"]
    volumes: ["./:/home/bun/app"]
